CREATE TABLE orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_name VARCHAR(200) NOT NULL,
  price INTEGER NOT NULL,
  count INTEGER NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP
  WITH
    TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
  WITH
    TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT orders_item_name_not_blank CHECK (btrim (item_name) <> ''),
    CONSTRAINT orders_price_non_negative CHECK (price >= 0),
    CONSTRAINT orders_count_positive CHECK (count > 0),
    CONSTRAINT orders_status_valid CHECK (status IN ('CREATED', 'PAID', 'SHIPPED'))
);
